### ISSUE TITLE
Nested routers routes that use regex do not get the base url.

### ISSUE THREAD

**Issue by velddev** [ukayani/restify-router#16]
I was trying to debug why my regexed route was not working. but it only accepted it from the base address, and not from the /v1/.../route. Maybe a good enhancement would be appending the regex?

**Comment by ukayani** [comment]
@velddev 

Could you provide a usage example for regex with prefix?

**Comment by velddev** [comment]
Hey uka an example of this is to do

```js
router.add('/gateway', require('./gateway.router'));

// in gateway
router.get(/^([0-9]+)/, (req, res) => {
   ...
});
```

**Comment by calvinlfer** [comment]
Hello @velddev, I think @ukayani was trying to find out your use case for prefixes combined with regular expression paths. 

To give you a bit of background, I am a bit hesitant on that PR since I have to manually escape some characters, and I am not sure whether all characters have been escaped correctly to provide proper regular expression behavior with prefix support.
